cmake_minimum_required(VERSION 3.16)
project(cel_teapot_preview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
find_package(Threads REQUIRED)
add_subdirectory(../../components/Jet/src Jet)
target_include_directories(Jet PUBLIC ../main/firmware)
add_executable(cel_teapot preview.cpp)
target_include_directories(cel_teapot PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(cel_teapot PRIVATE Jet Threads::Threads)
if(MSVC)
 target_compile_options(cel_teapot PRIVATE /UNDEBUG)
else()
 target_compile_options(cel_teapot PRIVATE -UNDEBUG)
endif()
add_test(NAME cel_teapot COMMAND cel_teapot)
foreach(test cel_quantization)
 add_executable(${test} ../../components/Jet/tests/${test}.cpp)
 target_link_libraries(${test} PRIVATE Jet)
 if(MSVC)
  target_compile_options(${test} PRIVATE /UNDEBUG)
 else()
  target_compile_options(${test} PRIVATE -UNDEBUG)
 endif()
 add_test(NAME ${test} COMMAND ${test})
endforeach()
