cmake_minimum_required(VERSION 3.16)
project(island_preview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
add_subdirectory(../../components/Jet/src Jet)
target_include_directories(Jet PUBLIC ../main/firmware)
add_executable(island preview.cpp)
target_include_directories(island PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(island PRIVATE Jet)
if(MSVC)
    target_compile_options(island PRIVATE /UNDEBUG)
else()
    target_compile_options(island PRIVATE -UNDEBUG)
endif()
add_test(NAME island COMMAND island)
add_executable(water_coverage water_coverage.cpp)
target_include_directories(water_coverage PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(water_coverage PRIVATE Jet)
if(MSVC)
    target_compile_options(water_coverage PRIVATE /UNDEBUG)
else()
    target_compile_options(water_coverage PRIVATE -UNDEBUG)
endif()
add_test(NAME water_coverage COMMAND water_coverage)
foreach(test water_reflection)
    add_executable(${test} ../../components/Jet/tests/${test}.cpp)
    target_link_libraries(${test} PRIVATE Jet)
    if(MSVC)
        target_compile_options(${test} PRIVATE /UNDEBUG)
    else()
        target_compile_options(${test} PRIVATE -UNDEBUG)
    endif()
    add_test(NAME ${test} COMMAND ${test})
endforeach()
