"""Generate Jet's Utah teapot mesh from the vendored FreeGLUT control points.

Run from any directory. No third-party Python packages are needed.
Analytic Bezier derivatives produce normals; no mesh loading occurs on device.
"""
from pathlib import Path
import math
import re
import hashlib

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / 'assets/fg_teapot_data.h'
OUTPUT = ROOT / 'main/TeapotMesh.hpp'
SUBDIVISIONS = 5
SCALE = 160

def cross(a, b):
    return (a[1]*b[2]-a[2]*b[1], a[2]*b[0]-a[0]*b[2], a[0]*b[1]-a[1]*b[0])

def basis(t):
    s = 1-t
    return (s*s*s, 3*t*s*s, 3*t*t*s, t*t*t), (-3*s*s, 3*s*s-6*t*s, 6*t*s-3*t*t, 3*t*t)

def parse(name):
    text = SOURCE.read_text()
    body = text.split('static '+('int ' if name.startswith('patch') else 'GLfloat ')+name, 1)[1]
    body = body.split('=', 1)[1].split('};', 1)[0]
    return [[float(v.rstrip('f')) for v in re.findall(r'-?\d+(?:\.\d+)?f?', row)]
            for row in re.findall(r'\{([^{}]+)\}', body)]

def evaluate(cp, u, v, patch):
    bu, du = basis(u)
    bv, dv = basis(v)
    p = [sum(bu[i]*bv[j]*cp[4*i+j][k] for i in range(4) for j in range(4)) for k in range(3)]
    a = [sum(bu[i]*dv[j]*cp[4*i+j][k] for i in range(4) for j in range(4)) for k in range(3)]
    b = [sum(du[i]*bv[j]*cp[4*i+j][k] for i in range(4) for j in range(4)) for k in range(3)]
    n = cross(a, b)
    if u == 0 and patch in (3, 5):
        n = (0, 1 if patch == 3 else -1, 0)
    length = math.sqrt(sum(c*c for c in n))
    assert length > 1e-9
    return p, [c / length for c in n]

def transform(v, copy, rotational):
    x, y, z = v
    if not rotational:
        return (x, y, -z if copy else z)
    return ((x,y,z), (z,y,-x), (-x,y,-z), (-z,y,x))[copy]

def main():
    patches, points = parse('patchdata_teapot'), parse('cpdata_teapot')
    assert len(patches) == 10 and len(points) == 129
    vertices, indices, seen = [], [], {}
    for patch, control in enumerate(patches):
        cp = [(points[int(i)][0], points[int(i)][2]-1.575, -points[int(i)][1]) for i in control]
        for copy in range(4 if patch < 6 else 2):
            grid = []
            for u in range(SUBDIVISIONS+1):
                row = []
                for v in range(SUBDIVISIONS+1):
                    p, n = evaluate(cp, u/SUBDIVISIONS, v/SUBDIVISIONS, patch)
                    p, n = transform(p,copy,patch<6), transform(n,copy,patch<6)
                    key = tuple(round(x*SCALE) for x in p) + tuple(round(x*1024) for x in n)
                    if key not in seen:
                        seen[key] = len(vertices)
                        vertices.append(key)
                    row.append(seen[key])
                grid.append(row)
            for u in range(SUBDIVISIONS):
                for v in range(SUBDIVISIONS):
                    a,b,c,d = grid[u][v],grid[u+1][v],grid[u+1][v+1],grid[u][v+1]
                    for triangle in [(a,b,c),(a,c,d)]:
                        p,q,r = [vertices[i] for i in triangle]
                        face = cross([q[i]-p[i] for i in range(3)], [r[i]-p[i] for i in range(3)])
                        if not any(face):
                            continue
                        dot = sum(face[i]*(p[i+3]+q[i+3]+r[i+3]) for i in range(3))
                        if dot < 0:
                            triangle = (triangle[0],triangle[2],triangle[1])
                        indices.append(triangle)
    assert len(vertices) < 65536
    lines = ['#pragma once', '// Generated by tools/generate_teapot.py; do not edit.',
             '// Utah teapot data: FreeGLUT. See assets/README.md and the vendored licence.',
             '// Source SHA256: '+hashlib.sha256(SOURCE.read_bytes()).hexdigest(),
             '#include "Object.hpp"', '#include <cstdint>', 'namespace TeapotMesh {',
             'inline constexpr int16_t vertices[][6] = {']
    lines += ['    {'+','.join(map(str,v))+'},' for v in vertices]
    lines += ['};', 'inline constexpr uint16_t triangles[][3] = {']
    lines += ['    {'+','.join(map(str,t))+'},' for t in indices]
    lines += ['};', '''inline Renderer::Object* create(Renderer::Material* material) {
    auto* mesh = new Renderer::Object();
    mesh->vertices.reserve(sizeof(vertices)/sizeof(vertices[0]));
    mesh->triangles.reserve(sizeof(triangles)/sizeof(triangles[0]));
    for (const auto& v : vertices)
        mesh->addVertex({{v[0],v[1],v[2]}, {0,0}, {v[3],v[4],v[5]}});
    for (const auto& t : triangles) mesh->addTriangle(t[0],t[1],t[2],material);
    mesh->calculateBoundingBox();
    mesh->cachePositions();
    return mesh;
}
}''']
    OUTPUT.write_text('\n'.join(lines)+'\n')
    print(f'Teapot: {len(vertices)} vertices, {len(indices)} triangles')

if __name__ == '__main__':
    main()
