cmake_minimum_required(VERSION 3.16)
project(woodland_preview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
find_package(Threads REQUIRED)
add_subdirectory(../../components/Jet/src Jet)
target_include_directories(Jet PUBLIC ../main/firmware)
add_executable(woodland preview.cpp)
target_include_directories(woodland PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(woodland PRIVATE Jet Threads::Threads)
if(MSVC)
 target_compile_options(woodland PRIVATE /UNDEBUG)
else()
 target_compile_options(woodland PRIVATE -UNDEBUG)
endif()
add_test(NAME woodland COMMAND woodland)
