cmake_minimum_required(VERSION 3.16)
project(courier_preview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
find_package(Threads REQUIRED)
add_subdirectory(../../components/Jet/src Jet)
target_include_directories(Jet PUBLIC ../main/firmware)
add_executable(courier preview.cpp)
target_include_directories(courier PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(courier PRIVATE Jet Threads::Threads)
if(MSVC)
 target_compile_options(courier PRIVATE /UNDEBUG)
else()
 target_compile_options(courier PRIVATE -UNDEBUG)
endif()
add_test(NAME courier COMMAND courier)
