"""Convert the supplied crate asset into a small RGB565 firmware resource."""
from pathlib import Path
import hashlib
from PIL import Image

root=Path(__file__).resolve().parents[1]
source=root/'assets/RTS_Crate.png'
output=root/'main/CrateTexture.hpp'
image=Image.open(source).convert('RGB').resize((128,128),Image.Resampling.BOX)
values=[((r>>3)<<11)|((g>>2)<<5)|(b>>3) for r,g,b in image.getdata()]
lines=['#pragma once','#include <cstdint>','// Cpt_Flash, CC0: https://opengameart.org/content/2d-wooden-box',
       '// Generated by tools/import_crate.py; source SHA256 '+hashlib.sha256(source.read_bytes()).hexdigest(),
       'namespace CrateTexture {','inline constexpr int width=128,height=128;',
       'inline const uint16_t pixels[] = {']
lines.extend(','.join(f'0x{x:04x}' for x in values[i:i+16])+',' for i in range(0,len(values),16))
lines+=['};','}']
output.write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
print(f'{output}: 128x128, {len(values)*2} RGB565 bytes')
