cmake_minimum_required(VERSION 3.16)
project(boxes_preview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
add_subdirectory(../../components/Jet/src Jet)
target_include_directories(Jet PUBLIC ../main/firmware)
add_executable(boxes preview.cpp)
target_include_directories(boxes PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(boxes PRIVATE Jet)
add_executable(texture_options ../../components/Jet/tests/texture_options.cpp)
target_link_libraries(texture_options PRIVATE Jet)
foreach(test boxes texture_options)
    if(MSVC)
        target_compile_options(${test} PRIVATE /UNDEBUG)
    else()
        target_compile_options(${test} PRIVATE -UNDEBUG)
    endif()
    add_test(NAME ${test} COMMAND ${test})
endforeach()
