cmake_minimum_required(VERSION 3.16)
project(car_preview LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
enable_testing()
find_package(Threads REQUIRED)
add_subdirectory(../../components/Jet/src Jet)
target_include_directories(Jet PUBLIC ../main/firmware)
add_executable(car preview.cpp)
target_include_directories(car PRIVATE ../main ../../components/esp32_jet)
target_link_libraries(car PRIVATE Jet Threads::Threads)
if(MSVC)
 target_compile_options(car PRIVATE /UNDEBUG)
else()
 target_compile_options(car PRIVATE -UNDEBUG)
endif()
add_test(NAME car COMMAND car)
foreach(test obj_loader environment_mapping unlit_spans)
 add_executable(${test} ../../components/Jet/tests/${test}.cpp)
 target_link_libraries(${test} PRIVATE Jet)
 if(MSVC)
  target_compile_options(${test} PRIVATE /UNDEBUG)
 else()
  target_compile_options(${test} PRIVATE -UNDEBUG)
 endif()
 add_test(NAME ${test} COMMAND ${test})
endforeach()
